apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: reduce-my-url
  labels:
    app: redis
spec:
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      name: redis
  selector:
    app: redis