apiVersion: v1
kind: Secret
metadata:
  name: reduce-my-url-secrets
  namespace: reduce-my-url
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secret.postgresDb | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
