apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: reduce-my-url
  labels:
    app: web
spec:
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
      name: http
  selector:
    app: web