apiVersion: v1
kind: Secret
metadata:
  name: reduce-my-url-secrets
  namespace: reduce-my-url
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
  POSTGRES_DB: shortener
  JWT_SECRET: change-this-in-production
